# Generated by Django 3.2.8 on 2021-10-25 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TYPER',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usertype', models.CharField(choices=[('O', 'owner'), ('C', 'customer')], max_length=2)),
                ('user', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='TYPE',
        ),
    ]
