# Generated by Django 3.2.8 on 2021-10-26 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkapp', '0002_auto_20211025_1601'),
    ]

    operations = [
        migrations.CreateModel(
            name='OWNER',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('phone_number', models.IntegerField()),
                # ('prices', models.IntegerField()),####
                ('city', models.CharField(choices=[('M', 'Mumbai'), ('D', 'Delhi'), ('K', 'Kolkata'), ('C', 'Chennai'), ('B', 'Banglore'), ('R', 'Rajasthan'), ('P', 'Punjab'), ('H', 'Hyderabad'), ('G', 'Gujrat'), ('L', 'Lucknow')], max_length=10)),
                ('address', models.CharField(max_length=100)),
            ],
        ),
    ]
