# Generated by Django 3.2.8 on 2021-10-29 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parkapp', '0004_auto_20211028_1529'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='image',
        ),
    ]
