# Generated by Django 3.2.8 on 2021-11-13 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkapp', '0006_alter_owner_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='BOOK',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=30)),
                ('customer', models.CharField(max_length=30)),
                ('key_num', models.IntegerField()),
                ('date', models.DateField(error_messages={'required': 'This field is required.'})),
                ('time', models.TimeField(error_messages={'required': 'This field is required.'})),
            ],
        ),
    ]
