# Generated by Django 3.2.8 on 2021-11-14 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkapp', '0007_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='bool_value',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
